### ISSUE TITLE
Sandbox test login credentials missing and new account not working

### ISSUE THREAD

**Issue by davidshumway** [agaveplatform/developer-docs#1]
On the docs page (https://docs.agaveplatform.org/#introduction) it states:

```
If you came here looking for a UI to interact with the platform and
kick the tires, please see our reference web application, Agave
ToGo, at https://togo.agaveplatform.org/.
```

But there are no details for logging in. For example, is there test account such as username: "demo", password: "demo"?

Furthermore, it's not allowing me to create a new user account on that page (https://togo.agaveplatform.org/). It keeps stating that the username or password is incorrect:

```
Error sending activation email.(401, '{"errors":["Bad username /
password"],"message":"error"}')
```

But it does not state what the issue is with the username or password. Are there invalid characters, too long, too short, etc.?

**Comment by deardooley** [comment]
We have updated the front page documentation. User registration is being updated to account for a change by our email provider. We expect to have it back up within the day. I'll update and close this issue at that time.

**Comment by deardooley** [comment]
Service has been restored to the new user registration app. You can visit the following URL to create a new account now: https://sandbox.agaveplatform.org/create_account.
